# Generated by Django 4.0.3 on 2022-03-17 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('academic_year', models.IntegerField(default=2000)),
                ('module_code', models.CharField(default='OOO', max_length=3)),
                ('semester', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('professor_id', models.CharField(default='OOO', max_length=4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('module_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profRate.module')),
                ('professor_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profRate.professor')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='professors',
            field=models.ManyToManyField(to='profRate.professor'),
        ),
    ]
