# Generated by Django 4.0.3 on 2022-03-18 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profRate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='module_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profRate.moduleinstance'),
        ),
    ]
